artifacts_root: artifacts
# An artifact is a byproduct of software development that helps describe the architecture, design and function of software.

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/